version: 2
jobs:
   build:
     docker:
       - image: circleci/node:7-browsers
     steps:
       - checkout
       - run: echo "Installing Global Dependencies"
       - run: sudo npm install -g ionic cordova 
       - run: echo "Installing Local Dependencies"
       - run: npm install
       - run: echo "Running Hello, World unit test..."
       - run: npm run test-ci
       - run: echo "Completed successfully"

